INSERT INTO us_products (product_title, brand, flavour, strength, format, nicotine_mg_pouch, td_element, description, page_url, image_url) VALUES 
('On! Wintergreen 8mg', 'ON', '! Wintergreen', '8mg', 'Slim', 8, 'ON', 'On! Wintergreen 8mg', 'https://prilla.com/us/on-nicotine-pouches/on-wintergreen-8', '/us-product-images/on_wintergreen_8mg_t_360.png'),
('On! Wintergreen 4mg', 'ON', '! Wintergreen', '4mg', 'Slim', 4, 'ON', 'On! Wintergreen 4mg', 'https://prilla.com/us/on-nicotine-pouches/on-wintergreen-4', '/us-product-images/on_wintergreen_4mg_t_360.png'),
('On! Wintergreen 2mg', 'ON', '! Wintergreen', '2mg', 'Slim', 2, 'ON', 'On! Wintergreen 2mg', 'https://prilla.com/us/on-nicotine-pouches/on-wintergreen-2', '/us-product-images/on_wintergreen_2mg_t_360.png'),
('On! Original 8mg', 'ON', '! Original', '8mg', 'Slim', 8, 'ON', 'On! Original 8mg', 'https://prilla.com/us/on-nicotine-pouches/on-original-8', '/us-product-images/on_original_8mg_t_360.png'),
('On! Original 4mg', 'ON', '! Original', '4mg', 'Slim', 4, 'ON', 'On! Original 4mg', 'https://prilla.com/us/on-nicotine-pouches/on-original-4', '/us-product-images/on_original_4mg_t_360.png'),
('On! Original 2mg', 'ON', '! Original', '2mg', 'Slim', 2, 'ON', 'On! Original 2mg', 'https://prilla.com/us/on-nicotine-pouches/on-original-2', '/us-product-images/on_original_2mg_t_360.png'),
('On! Mint 8mg', 'ON', '! Mint', '8mg', 'Slim', 8, 'ON', 'On! Mint 8mg', 'https://prilla.com/us/on-nicotine-pouches/on-mint-8', '/us-product-images/on_mint_8mg_t_360.png'),
('On! Mint 4mg', 'ON', '! Mint', '4mg', 'Slim', 4, 'ON', 'On! Mint 4mg', 'https://prilla.com/us/on-nicotine-pouches/on-mint-4', '/us-product-images/on_mint_4mg_t_360.png'),
('On! Mint 2mg', 'ON', '! Mint', '2mg', 'Slim', 2, 'ON', 'On! Mint 2mg', 'https://prilla.com/us/on-nicotine-pouches/on-mint-2', '/us-product-images/on_mint_2mg_t_360.png'),
('On! Coffee 8mg', 'ON', '! Coffee', '8mg', 'Slim', 8, 'ON', 'On! Coffee 8mg', 'https://prilla.com/us/on-nicotine-pouches/on-coffee-8', '/us-product-images/on_coffee_8mg_t_360.png'),
('On! Coffee 4mg', 'ON', '! Coffee', '4mg', 'Slim', 4, 'ON', 'On! Coffee 4mg', 'https://prilla.com/us/on-nicotine-pouches/on-coffee-4', '/us-product-images/on_coffee_4mg_t_360.png'),
('On! Coffee 2mg', 'ON', '! Coffee', '2mg', 'Slim', 2, 'ON', 'On! Coffee 2mg', 'https://prilla.com/us/on-nicotine-pouches/on-coffee-2', '/us-product-images/on_coffee_2mg_t_360.png'),
('On! Citrus 8mg', 'ON', '! Citrus', '8mg', 'Slim', 8, 'ON', 'On! Citrus 8mg', 'https://prilla.com/us/on-nicotine-pouches/on-citrus-8', '/us-product-images/on_citrus_8mg_t_360.png'),
('On! Citrus 4mg', 'ON', '! Citrus', '4mg', 'Slim', 4, 'ON', 'On! Citrus 4mg', 'https://prilla.com/us/on-nicotine-pouches/on-citrus-4', '/us-product-images/on_citrus_4mg_t_360.png'),
('On! Cinnamon 8mg', 'ON', '! Cinnamon', '8mg', 'Slim', 8, 'ON', 'On! Cinnamon 8mg', 'https://prilla.com/us/on-nicotine-pouches/on-cinnamon-8', '/us-product-images/on_cinnamon_8mg_t_360.png'),
('On! Citrus 2mg', 'ON', '! Citrus', '2mg', 'Slim', 2, 'ON', 'On! Citrus 2mg', 'https://prilla.com/us/on-nicotine-pouches/on-citrus-2', '/us-product-images/on_citrus_2mg_t_360.png'),
('On! Cinnamon 4mg', 'ON', '! Cinnamon', '4mg', 'Slim', 4, 'ON', 'On! Cinnamon 4mg', 'https://prilla.com/us/on-nicotine-pouches/on-cinnamon-4', '/us-product-images/on_cinnamon_4mg_t_360.png'),
('On! Cinnamon 2mg', 'ON', '! Cinnamon', '2mg', 'Slim', 2, 'ON', 'On! Cinnamon 2mg', 'https://prilla.com/us/on-nicotine-pouches/on-cinnamon-2', '/us-product-images/on_cinnamon_2mg_t_360.png'),
('NIC-S Wintergreen 6mg', 'NIC-S', 'Wintergreen', '6mg', 'Slim', 6, 'NIC-S', 'NIC-S Wintergreen 6mg', 'https://prilla.com/us/nic-s-nicotine-pouches/nic-s-wintergreen-6', '/us-product-images/nics_wintergreen_6mg_t_360.png'),
('NIC-S Wintergreen 3mg', 'NIC-S', 'Wintergreen', '3mg', 'Slim', 3, 'NIC-S', 'NIC-S Wintergreen 3mg', 'https://prilla.com/us/nic-s-nicotine-pouches/nic-s-wintergreen-3', '/us-product-images/nics_wintergreen_3mg_t_360.png');